# Generated by Django 5.2.11 on 2026-02-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('MANAGER', 'Fleet Manager'), ('DISPATCHER', 'Dispatcher'), ('SAFETY_OFFICER', 'Safety Officer'), ('FINANCIAL_ANALYST', 'Financial Analyst')], help_text='System role controlling permission scope.', max_length=20, unique=True),
        ),
    ]
