# Generated by Django 5.2.11 on 2026-02-21 05:13

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('REPAIR', 'Repair'), ('ROUTINE', 'Routine Service'), ('INSPECTION', 'Safety Inspection'), ('TYRE', 'Tyre Replacement'), ('ACCIDENT', 'Accident Repair'), ('OTHER', 'Other')], default='ROUTINE', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('description', models.TextField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, help_text='Total maintenance cost in INR.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('vendor', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maintenance Log',
                'verbose_name_plural': 'Maintenance Logs',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('REPAIR', 'Repair'), ('ROUTINE', 'Routine Service'), ('INSPECTION', 'Safety Inspection'), ('TYRE', 'Tyre Replacement'), ('ACCIDENT', 'Accident Repair'), ('OTHER', 'Other')], default='ROUTINE', max_length=20)),
                ('interval_type', models.CharField(choices=[('KM', 'Kilometre-based'), ('DAYS', 'Day-based'), ('BOTH', 'Whichever comes first')], default='DAYS', max_length=10)),
                ('interval_km', models.PositiveIntegerField(blank=True, help_text='Kilometre interval for scheduled service.', null=True)),
                ('interval_days', models.PositiveIntegerField(blank=True, help_text='Day interval for scheduled service.', null=True)),
                ('last_done_at', models.DateField(blank=True, null=True)),
                ('next_due_at', models.DateField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Maintenance Schedule',
                'verbose_name_plural': 'Maintenance Schedules',
                'ordering': ['next_due_at'],
            },
        ),
    ]
