# Generated by Django 5.2.11 on 2026-02-21 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_per_liter', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('odometer_at_fill', models.DecimalField(decimal_places=2, help_text='Odometer reading at the time of this fill-up.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fuel Log',
                'verbose_name_plural': 'Fuel Logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(db_index=True, help_text='Vehicle registration plate number.', max_length=20, unique=True)),
                ('make', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('year', models.PositiveSmallIntegerField()),
                ('color', models.CharField(blank=True, max_length=30)),
                ('vin', models.CharField(blank=True, help_text='17-char Vehicle Identification Number.', max_length=17, null=True, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_TRIP', 'On Trip'), ('IN_MAINTENANCE', 'In Maintenance'), ('DECOMMISSIONED', 'Decommissioned')], db_index=True, default='AVAILABLE', max_length=20)),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('CNG', 'CNG'), ('ELECTRIC', 'Electric')], default='DIESEL', max_length=10)),
                ('max_capacity_kg', models.DecimalField(decimal_places=2, help_text='Maximum payload capacity in kilograms.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('odometer_km', models.DecimalField(decimal_places=2, default=0, help_text='Current odometer reading in kilometres.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('INSURANCE', 'Insurance'), ('REGISTRATION', 'Registration'), ('INSPECTION', 'Fitness/Inspection'), ('PERMIT', 'Route Permit')], max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(db_index=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='vehicle_docs/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehicle Document',
                'verbose_name_plural': 'Vehicle Documents',
                'ordering': ['expires_on'],
            },
        ),
    ]
