# Generated by Django 5.2.11 on 2026-02-21 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='acquisition_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Purchase/lease cost of this vehicle in INR. Required for ROI calculation.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
